version: '3.8'

services:
  db:
    image:  library/postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: bookofaifosi
      POSTGRES_PASSWORD: bookofaifosi
      POSTGRES_DB: bookofaifosi