name: Deploy latest release

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Create Dockerfile
        run: sbt "Docker / publish"

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Fetch from dockerhub on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull aifosi/bookofaifosi
            docker compose -f bookofaifosi-compose.yml down
            docker compose -f bookofaifosi-compose.yml up -d
