name: Test if a PR compiles

on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile code
        run: sbt compile
